---
version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: black
          pkg-manager: pip
      - lint:
          command: |
            black .
          name: Lint - Black
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
      - run:
          command: |
            cd idemia
            python manage.py test
          name: Test
workflows:
  main:
    jobs:
      - build
