---
# This workflow will install Python dependencies and run tests

name: Deploy

on:
  push:
    branches:
      - feature/cicd-deploy-actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with Django unit tests
        run: |
          # Add the Cloud Foundry Foundation public key and package repository
          INSTALLER_FILE_NAME='cf-cli-installer.deb'
          wget -O $INSTALLER_FILE_NAME https://packages.cloudfoundry.org/stable?release=debian64&version=v7&source=github
          sudo apt install $INSTALLER_FILE_NAME

          # Deploy to cloud.gov
          cf --version
